name: app_setup_riverpod
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  local_auth: ^2.1.7
  permission_handler: ^11.0.1
  quick_actions: ^1.0.6
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/logo/
    - assets/icon/
